image: ondrejsika/ci

stages:
  - lint
  - build
  - test
  - deploy dev
  - deploy prod

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

  IMAGE: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG
  IMAGE_TESTS: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG

# lint:
#   image: node
#   stage: lint
#   script:
#     - yarn
#     - yarn run prettier-check

# editorconfig check:
#   image: mstruebing/editorconfig-checker
#   stage: lint
#   script:
#     - /ec


# build:
#   stage: build
#   variables:
#     COMPOSE_FILE: compose/main.yaml:compose/tests.yaml
#   script:
#     - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker-compose build
#     - docker-compose push


# test:
#   stage: test
#   variables:
#     COMPOSE_FILE: compose/main.yaml:compose/tests.yaml
#     COMPOSE_PROJECT_NAME: $CI_JOB_ID
#   script:
#     - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker-compose pull
#     - docker-compose run tests
#   after_script:
#     - docker-compose down

.deploy: &deploy_template
  stage: deploy dev
  variables:
    COMPOSE_FILE: compose/main.yaml:compose/traefik.yaml
    COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    DOCKER_HOST: $DOCKER_HOST_DEV
    HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$DEV_DOMAIN

deploy dev:
  <<: *deploy_template
  script:
    - docker-compose pull
    - docker-compose up -d
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$DEV_DOMAIN
    on_stop: stop dev

stop dev:
  <<: *deploy_template
  when: manual
  script:
    - docker-compose down
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop

deploy prod:
  stage: deploy prod
  variables:
    KUBECONFIG: .kubeconfig
    DEPLOY_NAME: $CI_PROJECT_PATH_SLUG
  script:
    - echo $KUBECONFIG_FILECONTENT | base64 -d > $KUBECONFIG
    - helm template ./helm/hello-world --name $DEPLOY_NAME --set image=$IMAGE --set host=$PROD_DOMAIN | kubectl apply -f -
  only:
    - master
  when: manual
  environment:
    name: $CI_PROJECT_PATH_SLUG
    url: https://$PROD_DOMAIN
