image: ondrejsika/ci

stages:
  - lint
  - build
  - test
  - deploy dev
  - deploy prod

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

  IMAGE: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG
  IMAGE_TESTS: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG

lint:
  image: node
  stage: lint
  script:
    - yarn
    - yarn run prettier-check

editorconfig check:
  image: mstruebing/editorconfig-checker
  stage: lint
  script:
    - /ec


build:
  stage: build
  variables:
    COMPOSE_FILE: compose/main.yaml:compose/test.yaml
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build
    - docker-compose push
