image: ondrejsika/ci

stages:
  - lint
  - build
  - test
  - deploy dev
  - deploy prod

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

  IMAGE: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG
  IMAGE_TESTS: $CI_REGISTRY_IMAGE/test:$CI_COMMIT_REF_SLUG

# lint:
#   image: node
#   stage: lint
#   script:
#     - yarn
#     - yarn run prettier-check

# editorconfig check:
#   image: mstruebing/editorconfig-checker
#   stage: lint
#   script:
#     - /ec


# build:
#   stage: build
#   variables:
#     COMPOSE_FILE: compose/main.yaml:compose/tests.yaml
#   script:
#     - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker-compose build
#     - docker-compose push


# test:
#   stage: test
#   variables:
#     COMPOSE_FILE: compose/main.yaml:compose/tests.yaml
#     COMPOSE_PROJECT_NAME: $CI_JOB_ID
#   script:
#     - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker-compose pull
#     - docker-compose run tests
#   after_script:
#     - docker-compose down

deploy dev:
  stage: deploy dev
  variables:
    COMPOSE_FILE: compose/main.yaml:compose/traefik.yaml
    COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    DOCKER_HOST: $DOCKER_HOST_DEV
    HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$DEV_DOMAIN
  script:
    - docker-compose pull
    - docker-compose up -d
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$DEV_DOMAIN
