image: ondrejsika/ci

stages:
  - lint
  - build
  - test
  - deploy dev
  - deploy prod

variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .next/

lint:
  image: node
  stage: lint
  script:
    - yarn
    - yarn run prettir-check

